BASE=..
include $(BASE)/Makefile.header

LIBRARIES = liblwk.a
HEADERS   = liblwk.h

# Put liblwk.h in include/lwk dir
HEADERS_SUBDIR = lwk

liblwk_SOURCES = syscalls.c pmem.c elf.c aspace.c arena.c

include $(BASE)/Makefile.footer
